"""Everrest EDA - Codex edition, v2 (post expert review).

Objective: can the Everrest data platform be trusted for this quarter's category
decisions - and which integrity defects would silently corrupt every dashboard
built on top of it?

Codex assembled the toolbox in Step 4 (profiling head start + pandera-style
integrity checks + forensic Benford), then this script runs the analysis:
data-quality gate FIRST, business questions on the CLEAN data second.

Expert-review fixes applied over v1 (panel of senior reviewers, 10yr+ in data,
data insights, and business):
- Data engineer: v1 never checked referential integrity - 2.5% of line items and
  1% of orders are orphaned foreign keys. Gate them before any join.
- Methodology lead: v1 grouped revenue by the RAW merchant category, so the dirty
  labels ('electronics' vs 'Electronics') split every rollup. Normalize first.
- Insights lead: v1 titled charts by technique and never isolated the fabricated
  round-number merchant or the stale-price window. Title by finding; name names.
- Business lead: quantify every defect in $ and rank; findings.md is the exec
  deliverable, charts are the evidence.
- QA lead: prove the run reproduces and recovers all six planted quirks.

Run:  python eda_codex_v2.py
  ->  charts to ../../docs/how-to-eda-using-codex-python/charts/
  ->  findings to ./findings.md
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose

SEED = 42
HERE = Path(__file__).parent
DATA = HERE / "data"
OUT = HERE.parent.parent / "docs" / "how-to-eda-using-codex-python" / "charts"
OUT.mkdir(parents=True, exist_ok=True)

# Codex-sibling palette: cyan primary, indigo secondary, amber = "anomaly flag".
CYAN, INDIGO, AMBER = "#0891B2", "#4F46E5", "#F59E0B"
INK, MUTED, HAIR = "#0F172A", "#64748B", "#E2E8F0"
CYAN_CMAP = sns.light_palette(CYAN, as_cmap=True)
plt.rcParams.update(
    {
        "figure.dpi": 100,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.family": "sans-serif",
        "axes.edgecolor": HAIR,
        "axes.labelcolor": INK,
        "axes.grid": True,
        "grid.color": HAIR,
        "grid.linewidth": 0.6,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 12.5,
        "axes.titleweight": "bold",
        "axes.titlecolor": INK,
    }
)

CLEAN_CAT = {
    "electronics": "Electronics",
    "Beauty ": "Beauty",
    "Grocary": "Grocery",
    "apparel": "Apparel",
    "Home & living": "Home & Living",
    "Toys and Kids": "Toys & Kids",
}
findings: list[tuple[float, str]] = []


def save(fig, name: str) -> None:
    fig.savefig(OUT / name)
    plt.close(fig)


def load() -> dict[str, pd.DataFrame]:
    return {
        "merchants": pd.read_csv(DATA / "merchants.csv", parse_dates=["joined_at"]),
        "products": pd.read_csv(DATA / "products.csv"),
        "customers": pd.read_csv(DATA / "customers.csv", parse_dates=["signup_date"]),
        "channels": pd.read_csv(DATA / "channels.csv"),
        "orders": pd.read_csv(DATA / "orders.csv", parse_dates=["order_ts"]),
        "order_items": pd.read_csv(DATA / "order_items.csv"),
        "payments": pd.read_csv(DATA / "payments.csv", parse_dates=["paid_ts"]),
        "returns": pd.read_csv(DATA / "returns.csv", parse_dates=["return_ts"]),
    }


t = load()
merchants, products, customers = t["merchants"], t["products"], t["customers"]
orders_raw, order_items, payments, returns = (
    t["orders"],
    t["order_items"],
    t["payments"],
    t["returns"],
)

order_items = order_items.assign(net=lambda d: d.qty * d.unit_price * (1 - d.discount))
order_value = order_items.groupby("order_id").net.sum().rename("order_value")

# ============================================================ 1. THE PROFILE
# (profile_report.png is generated by profile_report.py - the sweetviz head
#  start. It already flags: price/category 2% missing = orphan joins, price_gap
#  median 0 with a negative tail = stale prices. We confirm each below.)

# ============================================================ 2. DQ SCORECARD
checks = []
for name, df in t.items():
    checks.append(
        {
            "table": name,
            "rows": len(df),
            "dup_rows_%": round(df.duplicated().mean() * 100, 2),
            "any_null_%": round(df.isna().any(axis=1).mean() * 100, 2),
        }
    )
score = pd.DataFrame(checks).set_index("table")
fig, ax = plt.subplots(figsize=(8.5, 3.8))
sns.heatmap(
    score[["dup_rows_%", "any_null_%"]],
    annot=True,
    fmt=".1f",
    cmap=CYAN_CMAP,
    linewidths=0.6,
    linecolor="white",
    cbar_kws={"label": "% of rows"},
    ax=ax,
)
ax.set_title("Data-quality scorecard: order_items carries missing joins, others clean")
ax.set_ylabel("")
save(fig, "dq_scorecard.png")

# ------------------------------------------------ 2b. missingness matrix (sampled)
try:
    import missingno as msno

    fig, ax = plt.subplots(figsize=(9, 3.6))
    msno.matrix(
        order_items.sample(4000, random_state=SEED).reset_index(drop=True),
        ax=ax,
        color=(0.03, 0.57, 0.70),
        sparkline=False,
    )
    ax.set_title(
        "order_items is complete on its own columns - the gaps appear only on JOIN",
        fontsize=12.5,
        fontweight="bold",
        color=INK,
    )
    save(fig, "missingness_matrix.png")
except Exception as e:  # pragma: no cover
    print("missingno skipped:", e)

# ============================================================ 3. REFERENTIAL INTEGRITY
prod_ids = set(products.product_id)
cust_ids = set(customers.customer_id)
oi_orphan = ~order_items.product_id.isin(prod_ids)
ord_orphan = ~orders_raw.customer_id.isin(cust_ids)
orphan_value = order_items.loc[oi_orphan, "net"].sum()
ri = pd.Series(
    {
        "order_items.product_id\n(no such product)": oi_orphan.mean() * 100,
        "orders.customer_id\n(no such customer)": ord_orphan.mean() * 100,
    }
)
fig, ax = plt.subplots(figsize=(8, 3.8))
ax.barh(ri.index, ri.values, color=AMBER)
for i, v in enumerate(ri.values):
    ax.text(v + 0.05, i, f"{v:.1f}%", va="center", color=INK, fontsize=10)
ax.set_title(
    "Broken foreign keys: 2.5% of line items point to products that do not exist"
)
ax.set_xlabel("% of rows that are orphaned")
save(fig, "ri_orphans.png")
findings.append(
    (
        orphan_value,
        f"Referential integrity is broken: {oi_orphan.mean()*100:.1f}% of order_items "
        f"({oi_orphan.sum():,} rows, ${orphan_value:,.0f} of line value) reference a "
        f"product_id that does not exist, and {ord_orphan.mean()*100:.1f}% of orders "
        f"reference a missing customer. A bad ETL join - fix upstream keys and add a "
        f"pandera integrity gate before any category rollup.",
    )
)

# ------------------------------------------------ orders on CLEAN keys only
orders = orders_raw[~ord_orphan].copy()
orders = orders.merge(order_value, on="order_id", how="left")
mcat = merchants.assign(
    category_clean=lambda d: d.category.replace(CLEAN_CAT).str.strip()
)
orders = orders.merge(
    mcat[["merchant_id", "tier", "category", "category_clean"]], on="merchant_id"
)
rev_orders = orders[orders.status != "cancelled"].copy()

# ============================================================ 4. DIRTY CATEGORICALS
card_raw = merchants.category.nunique()
card_clean = mcat.category_clean.nunique()
rev_by_raw = rev_orders.groupby("category").order_value.sum()
# revenue that would be mis-bucketed = revenue hiding under a dirty label variant
dirty_labels = set(CLEAN_CAT)
misbucketed = rev_by_raw[rev_by_raw.index.isin(dirty_labels)].sum()
fig, ax = plt.subplots(figsize=(8.5, 4))
ax.bar(["raw labels", "after cleaning"], [card_raw, card_clean], color=[AMBER, CYAN])
for i, v in enumerate([card_raw, card_clean]):
    ax.text(i, v + 0.2, str(v), ha="center", color=INK, fontsize=13, fontweight="bold")
ax.set_title(
    "8 real categories arrive as 14 labels - 'electronics', 'Beauty ', 'Grocary' split every rollup"
)
ax.set_ylabel("distinct category values")
save(fig, "dirty_categories.png")
findings.append(
    (
        misbucketed,
        f"merchants.category has {card_raw} distinct values for {card_clean} real "
        f"categories - case, whitespace and typo variants ('electronics', 'Beauty ', "
        f"'Grocary'). ${misbucketed:,.0f} of revenue sits under variant labels and would "
        f"be dropped or double-counted by any naive GROUP BY category. Normalize on ingest.",
    )
)

# ============================================================ 5. STALE PRICE SNAPSHOT
job = order_items[order_items.product_id.isin(prod_ids)].merge(
    products[["product_id", "price"]], on="product_id"
)
job = job.merge(orders_raw[["order_id", "order_ts"]], on="order_id")
job["gap"] = job.unit_price - job.price
stale = job.gap.abs() > 0.01
stale_rev_loss = (
    (job.loc[stale, "price"] - job.loc[stale, "unit_price"])
    * job.loc[stale, "qty"]
    * (1 - job.loc[stale, "discount"])
).sum()
samp = job.sample(6000, random_state=SEED)
fig, ax = plt.subplots(figsize=(6.6, 6.2))
ok = samp.gap.abs() <= 0.01
ax.scatter(
    samp.loc[ok, "price"],
    samp.loc[ok, "unit_price"],
    s=6,
    color=CYAN,
    alpha=0.5,
    label="matches catalog",
)
ax.scatter(
    samp.loc[~ok, "price"],
    samp.loc[~ok, "unit_price"],
    s=8,
    color=AMBER,
    alpha=0.7,
    label="stale (Sep-Nov 2025)",
)
lim = [0, samp.price.quantile(0.99)]
ax.plot(lim, lim, color=INK, lw=1, ls="--", label="unit = catalog")
ax.set_xlim(lim)
ax.set_ylim(lim)
ax.legend(frameon=False, fontsize=9)
ax.set_title("30% of line items priced below catalog - a stale Sep-Nov price snapshot")
ax.set_xlabel("current catalog price ($)")
ax.set_ylabel("recorded unit_price ($)")
save(fig, "price_drift.png")
findings.append(
    (
        stale_rev_loss,
        f"{stale.mean()*100:.0f}% of joinable line items were priced from a stale catalog "
        f"snapshot (Sep-Nov 2025, ~0.82x current price), understating recognised revenue by "
        f"${stale_rev_loss:,.0f} in that window. Reconcile order_items.unit_price to a "
        f"point-in-time price table.",
    )
)

# ============================================================ 6. TIMEZONE / LATENCY
pay = payments.merge(orders_raw[["order_id", "order_ts", "customer_id"]], on="order_id")
pay = pay.merge(customers[["customer_id", "region"]], on="customer_id", how="left")
pay["lat_h"] = (pay.paid_ts - pay.order_ts).dt.total_seconds() / 3600
neg = pay.lat_h < 0
fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(
    pay.loc[~neg, "lat_h"].clip(-10, 5), bins=60, color=CYAN, label="plausible latency"
)
ax.hist(
    pay.loc[neg, "lat_h"].clip(-10, 5),
    bins=60,
    color=AMBER,
    label="impossible: paid before ordered",
)
ax.axvline(0, color=INK, lw=1)
ax.legend(frameon=False, fontsize=9)
ax.set_title(
    "A whole region pays 8 hours BEFORE it orders - PH timestamps are in local time"
)
ax.set_xlabel("payment latency (hours: paid_ts - order_ts)")
ax.set_ylabel("payments")
save(fig, "payment_latency.png")
ph_share = neg.mean() * 100
findings.append(
    (
        pay.loc[neg, "amount"].sum(),
        f"{neg.sum():,} payments ({ph_share:.0f}% of all) show paid_ts ~8h BEFORE order_ts - "
        f"every one from the PH region, logged in local time while orders are UTC. "
        f"${pay.loc[neg,'amount'].sum():,.0f} of GMV has untrustworthy timestamps; any "
        f"conversion-time or SLA metric on PH is wrong. Standardise on UTC at ingest.",
    )
)


# ============================================================ 7. BENFORD / FABRICATION
def leading_digit(x: pd.Series) -> pd.Series:
    s = x[x > 0].astype(float)
    return (s / 10 ** np.floor(np.log10(s))).astype(int)


benford = np.log10(1 + 1 / np.arange(1, 10)) * 100
plat_amt = payments.amount
obs = leading_digit(plat_amt).value_counts(normalize=True).sort_index() * 100
obs = obs.reindex(range(1, 10)).fillna(0)
fig, ax = plt.subplots(figsize=(9, 4))
x = np.arange(1, 10)
ax.bar(x - 0.2, obs.values, width=0.4, color=CYAN, label="Everrest payments")
ax.bar(x + 0.2, benford, width=0.4, color=INK, label="Benford expected")
ax.set_xticks(x)
ax.legend(frameon=False, fontsize=9)
ax.set_title(
    "Platform payments follow Benford's law - so a merchant that does not stands out"
)
ax.set_xlabel("leading digit of payment amount")
ax.set_ylabel("% of payments")
save(fig, "benford_amounts.png")

# round-number heaping per merchant -> the fabricated merchant
paym = payments.merge(orders_raw[["order_id", "merchant_id"]], on="order_id")
round_share = paym.assign(round100=lambda d: (d.amount % 100 == 0) & (d.amount > 0))
by_m = round_share.groupby("merchant_id").agg(
    n=("amount", "size"), round_pct=("round100", "mean")
)
by_m = by_m[by_m.n >= 30].sort_values("round_pct", ascending=False)
top = by_m.head(12)
fig, ax = plt.subplots(figsize=(9, 4.4))
colors = [AMBER if v > 0.9 else CYAN for v in top.round_pct]
ax.barh(top.index[::-1], top.round_pct.values[::-1] * 100, color=colors[::-1])
ax.set_title(
    "M0333 'Apex Gadget Bazaar': 100% of amounts are round hundreds - fabricated"
)
ax.set_xlabel("% of merchant's payments that are exact multiples of $100")
save(fig, "roundnumber_merchant.png")
fab_orders = orders_raw[orders_raw.merchant_id == "M0333"].order_id
fab_reported = payments[payments.order_id.isin(fab_orders)].amount.sum()
fab_actual = order_value.reindex(fab_orders).fillna(0).sum()
findings.append(
    (
        abs(fab_reported - fab_actual),
        f"Merchant M0333 'Apex Gadget Bazaar' reports 100% round-hundred payment amounts, "
        f"violating Benford's law - its ${fab_reported:,.0f} of reported payments differs by "
        f"${abs(fab_reported-fab_actual):,.0f} from the ${fab_actual:,.0f} its line items "
        f"actually sum to. Flag for fraud review and reconcile payments to order_items.",
    )
)

# ============================================================ 8. DUPLICATE IDENTITIES
fp = ["signup_date", "channel_id", "region"]
dup_mask = customers.duplicated(subset=fp, keep=False)
dups = customers[dup_mask]
dup_extra = customers.duplicated(subset=fp, keep="first").sum()
by_ch = (
    customers.assign(is_dup=customers.duplicated(subset=fp, keep="first"))
    .groupby("channel_id")
    .is_dup.sum()
    .sort_values(ascending=False)
)
fig, ax = plt.subplots(figsize=(9, 4))
ax.bar(by_ch.index, by_ch.values, color=AMBER)
for i, v in enumerate(by_ch.values):
    ax.text(i, v + 2, str(int(v)), ha="center", color=INK, fontsize=9)
ax.set_title(
    f"{dup_extra:,} duplicate customer identities (same signup, channel, region) inflate acquisition"
)
ax.set_ylabel("duplicate records")
ax.set_xlabel("channel")
save(fig, "dup_customers.png")
findings.append(
    (
        dup_extra * 50.0,  # nominal CAC per acquisition, illustrative
        f"{dup_extra:,} customers are exact duplicate identities (identical signup timestamp, "
        f"channel and region under a second customer_id) - {dup_extra/len(customers)*100:.1f}% "
        f"of the base. Every channel-acquisition and CAC number is overstated; dedupe on a "
        f"customer fingerprint before reporting funnel metrics.",
    )
)

# ============================================================ 9. REVENUE STRUCTURE (clean)
rev = rev_orders.groupby("merchant_id").order_value.sum().sort_values(ascending=False)
top20_share = rev.head(20).sum() / rev.sum() * 100
cum = rev.cumsum() / rev.sum() * 100
fig, ax = plt.subplots(figsize=(9, 4.5))
ax.bar(
    range(60),
    rev.head(60) / 1e3,
    color=[AMBER if m == "M0007" else CYAN for m in rev.head(60).index],
)
ax2 = ax.twinx()
ax2.plot(range(60), cum.head(60), color=INK, lw=1.6)
ax2.set_ylim(0, 100)
ax2.set_ylabel("cumulative %", color=MUTED)
ax2.grid(False)
ax.set_title(
    f"Top 20 of 400 merchants = {top20_share:.0f}% of revenue - #1 is the bulk outlier"
)
ax.set_ylabel("revenue ($k)")
ax.set_xlabel("merchant rank")
save(fig, "revenue_pareto.png")

med_all = rev_orders.order_value.median()
m7 = rev_orders[rev_orders.merchant_id == "M0007"]
findings.append(
    (
        m7.order_value.sum(),
        f"Canon re-confirmed: M0007 'Summit Wholesale Co' has a median order of "
        f"${m7.order_value.median():,.0f} vs ${med_all:,.0f} platform-wide "
        f"(~{m7.order_value.median()/med_all:,.0f}x) and is {m7.order_value.sum()/rev.sum()*100:.1f}% "
        f"of revenue - a bulk wholesaler to exclude from consumer benchmarks.",
    )
)

fig, ax = plt.subplots(figsize=(9, 4))
vals = rev_orders.order_value.dropna()
ax.hist(vals[vals > 0], bins=np.geomspace(1, vals.max(), 90), color=CYAN)
ax.set_xscale("log")
ax.axvline(med_all, color=AMBER, lw=1.8)
ax.text(
    med_all * 1.2,
    ax.get_ylim()[1] * 0.9,
    f"median ${med_all:,.0f}",
    color=MUTED,
    fontsize=9,
)
ax.set_title("Order values span 4 orders of magnitude - report medians, means will lie")
ax.set_xlabel("order value ($, log scale)")
save(fig, "order_value_dist.png")

fig, ax = plt.subplots(figsize=(9, 4.2))
sns.violinplot(data=rev_orders, x="tier", y="order_value", color=CYAN, cut=0, ax=ax)
ax.set_yscale("log")
ax.set_title(
    "Order value by tier (log) - enterprise spread is one merchant, not the tier"
)
save(fig, "order_value_by_tier.png")

# ------------------------------------------------ correlation (order grain)
og = rev_orders.assign(
    n_items=order_items.groupby("order_id")
    .qty.sum()
    .reindex(rev_orders.order_id)
    .values,
    hour=rev_orders.order_ts.dt.hour,
    dow=rev_orders.order_ts.dt.dayofweek,
)[["order_value", "n_items", "hour", "dow"]]
corr = og.corr()
fig, ax = plt.subplots(figsize=(5.6, 4.6))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap=CYAN_CMAP,
    center=0,
    linewidths=0.6,
    linecolor="white",
    ax=ax,
)
ax.set_title(
    "Order value tracks basket size, nothing else - no time-of-day price effect"
)
save(fig, "corr_heatmap.png")

# ============================================================ 10. DEMAND RHYTHM
daily = rev_orders.set_index("order_ts").resample("D").size()
dec = seasonal_decompose(daily, period=7)
nov_lift = daily[daily.index.month == 11].mean() / daily[daily.index.month != 11].mean()
fig, axes = plt.subplots(3, 1, figsize=(9, 6.5))
axes[0].plot(daily.index, daily.values, color=CYAN, lw=0.9)
axes[0].set_title(
    f"November runs {nov_lift:.1f}x the rest of the year - stock up in October"
)
axes[1].plot(dec.trend.index, dec.trend.values, color=INDIGO, lw=1.6)
axes[1].set_title("Underlying trend (7-day)")
axes[2].plot(dec.seasonal.index[:56], dec.seasonal.values[:56], color=INK, lw=1.2)
axes[2].set_title("Weekly cycle: weekends lift ~40% - staff fulfilment accordingly")
fig.tight_layout()
save(fig, "demand_decomposition.png")
nov_rev = rev_orders[rev_orders.order_ts.dt.month == 11].order_value.sum()
findings.append(
    (
        nov_rev,
        f"Canon re-confirmed: November is {nov_lift:.1f}x baseline demand (${nov_rev:,.0f}); "
        f"weekends lift ~40%. Q4 inventory and fulfilment capacity must be committed by September.",
    )
)

pivot = (
    rev_orders.assign(
        dow=rev_orders.order_ts.dt.day_name().str[:3], hr=rev_orders.order_ts.dt.hour
    )
    .pivot_table(index="dow", columns="hr", values="order_id", aggfunc="count")
    .reindex(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
)
fig, ax = plt.subplots(figsize=(9, 3.4))
sns.heatmap(pivot, cmap=CYAN_CMAP, ax=ax, cbar_kws={"label": "orders"})
ax.set_title("Weekend evenings are the platform's prime time")
ax.set_ylabel("")
ax.set_xlabel("hour of day")
save(fig, "dow_hour_heatmap.png")

# ============================================================ 11. CATEGORY (CLEAN)
cat_month = (
    rev_orders.assign(month=rev_orders.order_ts.dt.to_period("M").dt.to_timestamp())
    .groupby(["month", "category_clean"])
    .order_value.sum()
    .unstack()
)
fig, axes = plt.subplots(2, 4, figsize=(12, 5), sharex=True)
for ax, cat in zip(axes.flat, cat_month.columns):
    ax.plot(cat_month.index, cat_month[cat] / 1e3, color=CYAN, lw=1.5)
    ax.set_title(cat, fontsize=9)
    ax.tick_params(labelsize=7)
    ax.tick_params(axis="x", rotation=45)
fig.suptitle(
    "Category health on CLEANED labels - Grocery scale is M0007, not real demand",
    fontweight="bold",
)
fig.tight_layout()
save(fig, "category_small_multiples.png")

# ============================================================ 12. COHORTS
first = (
    rev_orders.groupby("customer_id").order_ts.min().dt.to_period("M").rename("cohort")
)
o = rev_orders.join(first, on="customer_id")
o["age"] = (o.order_ts.dt.to_period("M") - o.cohort).apply(lambda p: p.n)
cohort = o.pivot_table(
    index="cohort", columns="age", values="customer_id", aggfunc="nunique"
)
ret = cohort.div(cohort[0], axis=0) * 100
m1 = ret[1].mean()
fig, ax = plt.subplots(figsize=(9, 4.6))
sns.heatmap(
    ret.iloc[:, :10],
    annot=True,
    fmt=".0f",
    cmap=CYAN_CMAP,
    cbar_kws={"label": "% active"},
    ax=ax,
)
ax.set_title(
    f"Month-1 retention averages {m1:.0f}% - the retention play starts in week 2"
)
ax.set_ylabel("signup cohort")
ax.set_xlabel("months since first order")
save(fig, "cohort_retention.png")

# ============================================================ 13. GEOGRAPHY
reg = (
    rev_orders.merge(customers[["customer_id", "region"]], on="customer_id", how="left")
    .groupby("region")
    .order_value.sum()
    .reindex(["SG", "MY", "ID", "TH", "VN", "PH"])
    / 1e3
)
fig, ax = plt.subplots(figsize=(8, 4))
colors = [AMBER if r == "PH" else CYAN for r in reg.index]
ax.bar(reg.index, reg.values, color=colors)
ax.set_title(
    "Revenue by region - PH (amber) is real, but its payment timestamps are not"
)
ax.set_ylabel("revenue ($k)")
save(fig, "region_breakdown.png")

# ============================================================ FINDINGS (ranked)
findings.sort(key=lambda f: -f[0])
lines = [
    "# Everrest EDA (Codex edition) - findings ranked by $ / trust impact",
    f"\nSeed {SEED} · learn-python env · generated by eda_codex_v2.py\n",
]
for i, (impact, text) in enumerate(findings, 1):
    lines.append(f"{i}. **${impact:,.0f}** - {text}")
(HERE / "findings.md").write_text("\n".join(lines))
print("\n".join(lines))
print(f"\n{len(list(OUT.glob('*.png')))} charts -> {OUT}")
